repos:
  - repo: local
    hooks:
      - id: check-owner
        name: Check Owner In Model
        entry: ./hooks/commit-msg
        language: script
        types: [file]
        files: \.yml$

exit 0
